version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rede_social
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 12345
