# Utilize a imagem oficial do Java como base
FROM openjdk:17-jdk-slim

# Variável para armazenar o nome do JAR
ARG JAR_FILE=target/*.jar

# Copie o JAR da sua aplicação para a imagem
COPY ${JAR_FILE} redeSocialSpring-0.0.1-SNAPSHOT.jar

# Comando para executar a aplicação
ENTRYPOINT ["java","-jar","/app.jar"]
